env:
  folder: production-environment

spring:
  config:
    import: optional:configserver:http://configserver-service:8083

file:
  saver:
    service:
      url: http://bt-filemanager-service.ems.svc.cluster.local:8001/bt/s1/api/

eureka:
  client:
    enabled: false

app:
  resourceBaseUrl: "https://www.bottomhalf.in/bts/resources/"
