server:
  port: 8085

spring:
  profiles:
    active: default
  application:
    name: employee-project-service

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true



---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://localhost:8083

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/onlinedatabuilder
    username: istiyak
    password: live@Bottomhalf_001

#    url: jdbc:mysql://localhost:3306/onlinedatabuilder
#    username: root
#    password: istiyak@mi9

eureka:
  client:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://configserver-service:8083

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://194.233.76.48:3306/onlinedatabuilder
    username: istiyak
    password: live@Bottomhalf_011

eureka:
  client:
    enabled: false

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
