env:
  folder: local-environment

spring:
  config:
    #    activate:
    #      on-profile: default
    import: optional:configserver:http://localhost:8083

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinedatabuilder
    username: root
    password: istiyak@mi9

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka