env:
  folder: development-environment

spring:
  config:
    import: optional:configserver:http://localhost:8083

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.101:3306/onlinedatabuilder
#    username: istiyak
#    password: live@Bottomhalf_001

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://194.233.76.48:3306/ems_master
    username: istiyak
    password: live@Bottomhalf_011

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka